// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGvD-DpBm3KZO5w704AZqd4C2bEuKwdw',
    appId: '1:803177941128:web:20e2f515b4da54f4ff373d',
    messagingSenderId: '803177941128',
    projectId: 'pace-fb2fc',
    authDomain: 'pace-fb2fc.firebaseapp.com',
    storageBucket: 'pace-fb2fc.appspot.com',
    measurementId: 'G-2WDK2Y97HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXRgW1edp8OfP1HMzNE3l3drOb-8C5Is',
    appId: '1:803177941128:android:6c5c416bf4d64f68ff373d',
    messagingSenderId: '803177941128',
    projectId: 'pace-fb2fc',
    storageBucket: 'pace-fb2fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTx8VPA-IEHKS7nZfvPs9_sL5bgeF5Og',
    appId: '1:803177941128:ios:596e7315787ef9e0ff373d',
    messagingSenderId: '803177941128',
    projectId: 'pace-fb2fc',
    storageBucket: 'pace-fb2fc.appspot.com',
    iosClientId: '803177941128-6kko7gvaciq7kn9j2vehpe7jj924fovr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTx8VPA-IEHKS7nZfvPs9_sL5bgeF5Og',
    appId: '1:803177941128:ios:b793cc2528f392a3ff373d',
    messagingSenderId: '803177941128',
    projectId: 'pace-fb2fc',
    storageBucket: 'pace-fb2fc.appspot.com',
    iosClientId: '803177941128-ujss44tjaunercuefbv9v3vihk8hloje.apps.googleusercontent.com',
    iosBundleId: 'com.example.pace.RunnerTests',
  );
}
